### ISSUE TITLE
Use sliding DFT for CQT/VQT mode + IIR filter bank (analog-style analyzer)

### ISSUE THREAD

**Issue by TF3RDL** [stuerp/foo_vis_spectrum_analyzer#1]
I recently just looked at the [code related to CQT/VQT functionality](https://github.com/stuerp/foo_vis_spectrum_analyzer/blob/master/Analyzers/CQTAnalyzer.cpp) and it is in fact a Goertzel algorithm (which is fine only if you want to analyze smaller number of frequencies like in the case of DTMF signals, but it is very CPU-intensive for a full-range spectrum analyzer). So would be nice to use [sliding DFT](https://gist.github.com/TF3RDL/1810c570bad4f75f77941c981c65723f) (and its derivatives like [sliding windowed infinite Fourier transform](https://gist.github.com/TF3RDL/0f20d771ad92841d8a30d448f1140e6e), which is basically an IIR filter bank) as a backend for CQT/VQT part since it re-uses the previous output instead of re-calculating the entire thing from scratch (which improves performance) right?

I'm also thinking about an [IIR](https://github.com/vinniefalco/DSPFilters) bandpass filter bank-based spectral analysis like [Spectralissime](https://vb-audio.com/Spectralissime/), which is similar to sliding windowed infinite Fourier transform except the frequency response of these filters are symmetric in a logarithmic frequency scale (not exactly logarithmic due to cramping at near Nyquist frequency)

BTW, are any drawbacks of using sDFT/SWIFT over current Goertzel algorithm implementation for CQT/VQT mode?

**Comment by TF3RDL** [comment]
For replacing Goertzel algorithm with sliding DFT (which works better for larger number of bands), the window function has to be implemented in frequency-domain instead of time-domain (just like Brown-Puckette method as in showcqt filter from FFmpeg), but any window functions other than cosine sums can be easily implemented via [this paper](https://www.zafarrafii.com/Documents/Journals/Rafii%20-%20Sliding%20Discrete%20Fourier%20Transform%20with%20Kernel%20Windowing%20-%202018.pdf) (which basically uses the output of FFT of windowing functions to generate a sparse kernel for use with sliding DFT)

BTW, I have the [CodePen project](https://codepen.io/TF3RDL/details/MWLzPoO) showcasing analog-style analyzer and sliding DFT visualizations (which is a mockup of obviously-nonexistent [foo_cqt_analyzer](https://fanon.fandom.com/wiki/CQT_Analyzer) component) to show what I really meant by these

**Comment by TF3RDL** [comment]
The thing is that analog-style and sliding DFT analyzers needs this:
`if (_VisualisationStream->get_chunk_absolute(Chunk, PrevPlaybackTime, PlaybackTime - PrevPlaybackTime))`
`  ProcessAudioChunk(Chunk);`
`PrevPlaybackTime = PlaybackTime;` (where `PrevPlaybackTime` is where the previous playback time since last calculation)
instead of:
`if (_VisualisationStream->get_chunk_absolute(Chunk, PlaybackTime - (WindowSize / (ReactionAlignment/2.0+0.5)), WindowSize))`
`  ProcessAudioChunk(Chunk)` (where "reaction alignment" parameter is set to 0.5, therefore it is the same as currently has, but the parameter can be customizable latter, especially the Enhanced Spectrum Analyzer having time offset way ahead of the playback, proportional to the FFT size in samples, not half of them as in original Musical Spectrum)
in order to be calculated correctly and other analyzers would prefer latter sample acquisition method

**Comment by stuerp** [comment]
> The thing is that analog-style and sliding DFT analyzers needs this: `if (_VisualisationStream->get_chunk_absolute(Chunk, PrevPlaybackTime, PlaybackTime - PrevPlaybackTime))` ` ProcessAudioChunk(Chunk);` `PrevPlaybackTime = PlaybackTime;` (where `PrevPlaybackTime` is where the previous playback time since last calculation) instead of: `if (_VisualisationStream->get_chunk_absolute(Chunk, PlaybackTime - (WindowSize / (ReactionAlignment/2.0+0.5)), WindowSize))` ` ProcessAudioChunk(Chunk)` (where "reaction alignment" parameter is set to 0.5, therefore it is the same as currently has, but the parameter can be customizable latter, especially the Enhanced Spectrum Analyzer having time offset way ahead of the playback, proportional to the FFT size in samples, not half of them as in original Musical Spectrum) in order to be calculated correctly and other analyzers would prefer latter sample acquisition method

I tried that but it did not produce the right behavior. If I remember correctly there the spectrum lagged behind the sound, especially when compare with Enhanced Spectrum Analyzer.

**Comment by stuerp** [comment]
> I recently just looked at the [code related to CQT/VQT functionality](https://github.com/stuerp/foo_vis_spectrum_analyzer/blob/master/Analyzers/CQTAnalyzer.cpp) and it is in fact a Goertzel algorithm (which is fine only if you want to analyze smaller number of frequencies like in the case of DTMF signals, but it is very CPU-intensive for a full-range spectrum analyzer). So would be nice to use [sliding DFT](https://gist.github.com/TF3RDL/1810c570bad4f75f77941c981c65723f) (and its derivatives like [sliding windowed infinite Fourier transform](https://gist.github.com/TF3RDL/0f20d771ad92841d8a30d448f1140e6e), which is basically an IIR filter bank) as a backend for CQT/VQT part since it re-uses the previous output instead of re-calculating the entire thing from scratch (which improves performance) right?
> 
> I'm also thinking about an [IIR](https://github.com/vinniefalco/DSPFilters) bandpass filter bank-based spectral analysis like [Spectralissime](https://vb-audio.com/Spectralissime/), which is similar to sliding windowed infinite Fourier transform except the frequency response of these filters are symmetric in a logarithmic frequency scale (not exactly logarithmic due to cramping at near Nyquist frequency)
> 
> BTW, are any drawbacks of using sDFT/SWIFT over current Goertzel algorithm implementation for CQT/VQT mode?

You're asking me? You're the math guy ;-)

**Comment by stuerp** [comment]
> For replacing Goertzel algorithm with sliding DFT (which works better for larger number of bands), the window function has to be implemented in frequency-domain instead of time-domain (just like Brown-Puckette method as in showcqt filter from FFmpeg), but any window functions other than cosine sums can be easily implemented via [this paper](https://www.zafarrafii.com/Documents/Journals/Rafii%20-%20Sliding%20Discrete%20Fourier%20Transform%20with%20Kernel%20Windowing%20-%202018.pdf) (which basically uses the output of FFT of windowing functions to generate a sparse kernel for use with sliding DFT)
> 
> BTW, I have the [CodePen project](https://codepen.io/TF3RDL/details/MWLzPoO) showcasing analog-style analyzer and sliding DFT visualizations (which is a mockup of obviously-nonexistent [foo_cqt_analyzer](https://fanon.fandom.com/wiki/CQT_Analyzer) component) to show what I really meant by these

But why are there 2 other frequency spikes at 650 and 700 Hz when I feed it a 440 + 880Hz sample? Also, enabling the "NC method" switch only produces this 'clean' result. Everything else produces too much noise:

![image](https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/16443499/c6bdb1c3-ad4e-420c-8a27-92408ab3c0cb)

**Comment by stuerp** [comment]
First implementation attempt of SWIFT:
![image](https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/16443499/85661cc6-963d-4f85-805b-124f424e5625)
Does not look right to me. What do the values of the output of the sDFT represent? I know they're scaled between 0 and 1 but what is the unit?

**Comment by TF3RDL** [comment]
> > For replacing Goertzel algorithm with sliding DFT (which works better for larger number of bands), the window function has to be implemented in frequency-domain instead of time-domain (just like Brown-Puckette method as in showcqt filter from FFmpeg), but any window functions other than cosine sums can be easily implemented via [this paper](https://www.zafarrafii.com/Documents/Journals/Rafii%20-%20Sliding%20Discrete%20Fourier%20Transform%20with%20Kernel%20Windowing%20-%202018.pdf) (which basically uses the output of FFT of windowing functions to generate a sparse kernel for use with sliding DFT)
> > BTW, I have the [CodePen project](https://codepen.io/TF3RDL/details/MWLzPoO) showcasing analog-style analyzer and sliding DFT visualizations (which is a mockup of obviously-nonexistent [foo_cqt_analyzer](https://fanon.fandom.com/wiki/CQT_Analyzer) component) to show what I really meant by these
> 
> But why are there 2 other frequency spikes at 650 and 700 Hz when I feed it a 440 + 880Hz sample? Also, enabling the "NC method" switch only produces this 'clean' result. Everything else produces too much noise:
> 
> ![image](https://private-user-images.githubusercontent.com/16443499/303863867-c6bdb1c3-ad4e-420c-8a27-92408ab3c0cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2OTgyMTUsIm5iZiI6MTcwNzY5NzkxNSwicGF0aCI6Ii8xNjQ0MzQ5OS8zMDM4NjM4NjctYzZiZGIxYzMtYWQ0ZS00MjBjLThhMjctOTI0MDhhYjNjMGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDAwMzE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOGE3NjUxOWJlYWQ4OGUyMGMwMDExYjIyYjIwNzgyNmNiNWM2Y2MzYmQ5YmJhOGU0ODk1M2EwYjUyMjEwZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XsZ0BbbRM64pARoITys4jmBrfTZ4oifccxUt8oDcP28)

These two extraneous spikes (which nobody can hear that anyway) are artifacts of the NC method, and the artifacts the image above shows are exactly the same for me (so there is nothing we can do about it):
![nc method artifacts](https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/102759506/dc8c19a3-f582-4ac1-8969-dcb225b8b590)

> First implementation attempt of SWIFT: ![image](https://private-user-images.githubusercontent.com/16443499/303939059-85661cc6-963d-4f85-805b-124f424e5625.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2OTgyMTUsIm5iZiI6MTcwNzY5NzkxNSwicGF0aCI6Ii8xNjQ0MzQ5OS8zMDM5MzkwNTktODU2NjFjYzYtOTYzZC00Zjg1LTgwNWItMTI0ZjQyNGU1NjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDAwMzE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1NThhMDFhMDhjNGE2MmJiMTE1ZTkyZjYyOTkwZGM3MTY1ZTg1MGQzY2JhNjE4MWVlNDUwYmE1ZThjYWE0ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kTJ49sQi2xPT1zCvuIq29AVYbeJRMLgB0yr-eExK-sA) Does not look right to me. What do the values of the output of the sDFT represent? I know they're scaled between 0 and 1 but what is the unit?

The actual output of the SWIFT (after converting into magnitude from complex-valued output) is the same unitless values (0 corresponds to -Infinity dBFS, 0.5 is approximately -6dBFS, and 1 is 0dBFS) as other spectrum analyzer types

BTW, that image above the second quote doesn't look right and what does really a SWIFT would actually look like:
![spectrum of 440 and 880 tones](https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/102759506/82ab392d-a7ab-4764-9a58-8c68b89b8d67)
As I said before, a proper way to calculate SWIFT/sDFT/analog-style/IIR filter bank analyzer would involve making sure that the audio chunk acquisition only get new samples since last calculation

Also, the asymmetric response of the SWIFT (actually symmetric in linear frequency scale as opposed to logarithmic for biquad filter bank) means the bass boosted songs literally masks the higher frequencies (especially when the filter order is below 2)

**Comment by stuerp** [comment]
>  As I said before, a proper way to calculate SWIFT/sDFT/analog-style/IIR filter bank analyzer would involve making sure that the audio chunk acquisition only get new samples since last calculation

I missed that remark and it did the trick:

![image](https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/16443499/ed9953a4-e68b-450a-bbdc-e80510a1dec5)

Synthethic 440Hz sine wave with a little noise. 

- Any reason why no window function is applied to the time domain?
- Is the bandwidth parameter an integer or is it a real number between 0 and 8?

I'll expose it in the next version. First I have to get v0.7.0 released.

**Comment by TF3RDL** [comment]
> * Any reason why no window function is applied to the time domain?

Definitely, it is not possible to apply any time-domain windowing function to any of sDFT algorithms, but it is possible to implement that in the frequency-domain but it is only relevant on VQ-sDFT (complex-valued recursive FIR filter bank)
> * Is the bandwidth parameter an integer or is it a real number between 0 and 8?

The bandwidth parameter is a real number with the minimum value of 0 (constant-bandwidth), not an integer value

BTW, both SWIFT and analog-style analyzer can have infinite max window size as it is IIR and the max time resolution can be controlled by the same "FFT size" parameter for consistency with other analyzer algorithms

**Comment by stuerp** [comment]
@TF3RDL , I assume this issue can be closed?

**Comment by TF3RDL** [comment]
Probably, but the traditional FIR-based sDFT (the [VQ-sDFT](https://www.youtube.com/watch?v=G6YZKf_XZYg) algorithm) would benefit from AVX2 instruction set utilization, performance-wise (assuming it is done properly) as it might uses up more CPU than SWIFT and analog-style analyzer combined as I anticipated by experiencing a bad performance with 1/24th octave spectrum with Hann-windowed CQ-sDFT (w/ peak decay calculated during sDFT calculation) on my own WebAudio project that uses AudioWorklets

BTW, the bandpass filter design I've implemented in JS for [my CodePen project](https://codepen.io/TF3RDL/pen/MWLzPoO) is simply stacking the exact same second-order/biquad bandpass filter together multiple times in this case of `order` parameter is more than one, so therefore, it is not compliant with [ANSI S1.11-2004](https://law.resource.org/pub/us/cfr/ibr/002/ansi.s1.11.2004.pdf) specifications, but for a visualization component like this, it is actually fine (though the Enhanced Spectrum analyzer might use ANSI-compliant IIR filter bank if Crossover adds the analog-style analyzer mode)
