### ISSUE TITLE
Recommendation: Follow the DUI or CUI color configuration of the foobar2000

### ISSUE THREAD

**Issue by simear2004** [stuerp/foo_vis_spectrum_analyzer#2]
The current color configuration is unique and cannot be compared with the DUI or CUI color configuration that follows foobar2000, if I switch between light and dark or other colors in DUI or CUI, then you have to go to the component settings to set it.

**Comment by stuerp** [comment]
Is that the most logical behavior? The spectrum is basically eye candy. I could use the colors as a starting point but after that I think the user should be able to deviate. Your thoughts?

**Comment by simear2004** [comment]
You can refer to the color processing methods of the two visualization components foo_enhanced_spectrum_analyzer and foo_loudness_peakmeter, which can use user-defined colors or the system color configuration of DUI and CUI.

These two components could only use custom colors at first. After user feedback, they matched the system colors of DUI and CUI. The colors in View-Layout-Quick Settings are all accurately presented, and have a good visual affinity for the entire theme interface.

**Comment by TF3RDL** [comment]
Also, the feature to use DUI/CUI's color configuration instead should be a default setting for consistency with built-in visualizations of foobar2000, and yes, even the original foo_musical_spectrum don't have a feature to automatically set colors according to the system color configuration of DUI and CUI

**Comment by stuerp** [comment]
> You can refer to the color processing methods of the two visualization components foo_enhanced_spectrum_analyzer and foo_loudness_peakmeter, which can use user-defined colors or the system color configuration of DUI and CUI.
> 
> These two components could only use custom colors at first. After user feedback, they matched the system colors of DUI and CUI. The colors in View-Layout-Quick Settings are all accurately presented, and have a good visual affinity for the entire theme interface.

All visual elements can now be styled individually with each of the DUI or CUI colors in 0.7.0-RC-2,
