### ISSUE TITLE
Background Albumart not working

### ISSUE THREAD

**Issue by Rexadev** [stuerp/foo_vis_spectrum_analyzer#28]
### Background image in Full Screen and Panel Mode
![Bug foo_vis](https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/62152714/2c289777-62fb-4572-9051-dd48f8b6eb5c)
![Recording 2024-03-03 225529](https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/62152714/ebc90cd0-055c-49b8-bc77-1b7615c413ff)

## Related Issues 
1. https://github.com/stuerp/foo_vis_spectrum_analyzer/issues/38
2. https://github.com/stuerp/foo_vis_spectrum_analyzer/issues/17

**Comment by stuerp** [comment]
Fullscreen mode I can't fix. A fullscreen version is a separate instance of the component. The component does not know it's in fullscreen mode.

The background image I'll look into.

Again, you have set the settings for fullscreen separately. It's a different instance of the component, at least for DUI. In CUI is the same instance.

**Comment by stuerp** [comment]
Because you activate background art while a track is playing the fullscreen version of the component does not receive the artwork notification until the next track plays. Not intuitive but perfectly explainable and working as designed.

**Comment by stuerp** [comment]
@Rexadev, 
Is there still a problem or do the explanations clarify the behavior?

**Comment by Rexadev** [comment]
> Because you activate background art while a track is playing the fullscreen version of the component does not receive the artwork notification until the next track plays. Not intuitive but perfectly explainable and working as designed.

# 1. That is not the case

![Recording 2024-03-03 225529](https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/62152714/ebc90cd0-055c-49b8-bc77-1b7615c413ff)

# 2. Also there is note and hertz issue in main thread

# 3. Also there is "Full screen mode and exit is flipped"

# 4.  Please allow posting of .mp4 in repo

@stuerp

**Comment by Rexadev** [comment]
# Latest version shows frequency in X axis
![image](https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/62152714/a3441e0f-1195-46b9-887c-76bd693b9fd2)

@stuerp

**Comment by Rexadev** [comment]
Please allow posting of .mp4 in repo

@stuerp

**Comment by stuerp** [comment]
> > Because you activate background art while a track is playing the fullscreen version of the component does not receive the artwork notification until the next track plays. Not intuitive but perfectly explainable and working as designed.
> 
> # That is not the case
> Check main thread

My answer still stands. A fullscreen version in DUI is a separate instance. You can change the settings as much as you want, it'll only kick in when the next track plays. I don't know of a way to inherit settings from the windowed version. That would be more user-friendly.

**Comment by Rexadev** [comment]
> I don't know of a way to inherit settings from the windowed version

Config Profiles ? https://github.com/stuerp/foo_vis_spectrum_analyzer/issues/38

@stuerp please also check other bugs I have posted about in main thread

**Comment by stuerp** [comment]
> > I don't know of a way to inherit settings from the windowed version
> 
> Config Profiles ? #38

If it were that simple it would already have been implemented. There is no API for that.
 
> @stuerp please also check other bugs I have posted about in main thread

No. One bug or feature, one issue. I don't have the time to go hunting through  messages.

**Comment by Rexadev** [comment]
@stuerp you should ask Crossover to work with you he is developing a closed source component [foo_enhanced_spectrum_analyzer](https://wiki.hydrogenaud.io/index.php?title=Foobar2000:Components/Enhanced_Spectrum_Analyzer_(foo_enhanced_spectrum_analyzer))
