### ISSUE TITLE
Lagging while plays DSD audio (*.dff)

### ISSUE THREAD

**Issue by palashman** [stuerp/foo_vis_spectrum_analyzer#29]
Hi!
Spectrum bars become tranquillizered (lag) when play DSD files, no matter stereo or multichannel. At the same time old foo_musical_spectrum shows proper update rate.

Please see screen record (gif) with different audio formats (DSD, DST, flac):  https://disk.yandex.ru/i/d99AWCzaYXK3cQ

**Comment by stuerp** [comment]
I don't know what to look for. Lag how? What's DSD? Same settings or not? So many questions...

**Comment by palashman** [comment]
>What's DSD?
https://en.wikipedia.org/wiki/Direct_Stream_Digital

>Lag how?
Have you seen gif?

**Comment by stuerp** [comment]
Yes, I've seen the GIF. It's one frame.

**Comment by palashman** [comment]
Didn't guess to download it? -)))

**Comment by stuerp** [comment]
Look, I'm willing to help but stay polite. I don't speak Russian and I'm not going guess what you mean.

**Comment by stuerp** [comment]
No decent response. I don't have time for this.
