### ISSUE TITLE
High number of bands make certain frequencies "fall" when paused

### ISSUE THREAD

**Issue by WagnerGFX** [stuerp/foo_vis_spectrum_analyzer#36]
### Where?
- Configure Window > Frequencies > No. of bands

### How it's working now:
- When the number of bands reach 200 or above, some frequency bands seem to lower or disappear when pausing.
- Quite visible in 256, 300 and 400 bands
- Bigger numbers or different musics may look a bit better, but you can still see a lot of individual bands with the issue.
(they are just not "banded" together 😁)
- Freezing the visualizer still works as expected.

![freq bands](https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/16827309/b3e9cb28-c8d7-47b1-90e1-44fd37f641b4)

### Expected behavior:
- Those bands should freeze in place like the others when pausing.

### System Info:
- Windows 10 22H2
- Foobar2000 v1.6.16
- Visualizer v0.7.2.0
- CPU i7-2600k
- GPU GTX 1650

### Note:
- I'm aware the requirements say Foobar2000 v2.0, but I cannot use it yet due to some components still not supporting it (mostly Spider Monkey Panel).
- If the bug is exclusive to versions lower than v2.0, then the issue can be closed.

**Comment by stuerp** [comment]
Thank for your detailed report but I am unable to reproduce this. Even at the maximum setting of 512 with various sample rates the spectrum gets calculated correctly.

**Comment by WagnerGFX** [comment]
> Thank for your detailed report but I am unable to reproduce this. Even at the maximum setting of 512 with various sample rates the spectrum gets calculated correctly.

I thought it was the number of bands, but after testing other options, I've found that the settings in Transform seem to affect this much more.

![transform](https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/16827309/98f6035b-cc2d-41dd-977c-bc398e77dfd2)

**Window Functions affected:**
- Boxcar
- Hann (when Window Skew = 0.00)
- Every function between "Welch" and "Hyperbolic secant"

**No. of Bins** = 8192 or lower
**Mapping** = Standard
Enable **Smooth lower Frequencies**

**Comment by stuerp** [comment]
Tried to reproduce this without success. Could you attach a preset file with the settings that cause this issue?

**Comment by WagnerGFX** [comment]
[bands presets.zip](https://github.com/stuerp/foo_vis_spectrum_analyzer/files/14628559/bands.presets.zip)

BandsTest result in the bands showing a hole like below:

![bands result](https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/16827309/a43568b7-246c-4dab-a9f3-8da44c68f865)

BandsMinimum should result in nearly nothing showing:

![bands minimum](https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/16827309/b89261af-d604-4c86-86e8-df76cc1c8a83)

**Comment by stuerp** [comment]
Not here. This is BandsMinimum:
![image](https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/16443499/09539512-71d1-44fa-bd5e-eb608d4fdf3b)

**Comment by WagnerGFX** [comment]
> Not here. This is BandsMinimum

It's not fair if you fix the issue before taking the screenshot 🤣
The alpha version doesn't present the issue for me too, maybe it was the side effect of another issue.

The only change I noticed is that whenever I change the settings while paused, all bars disappear until I resume playing the song. It's nothing critical, but it gets harder to evaluate subtle changes.

**Comment by stuerp** [comment]
> > Not here. This is BandsMinimum
> 
> It's not fair if you fix the issue before taking the screenshot 🤣 The alpha version doesn't present the issue for me too, maybe it was the side effect of another issue.

Not intentionally. This version contains a couple code cleanups to make sure the spectrum amplitudes have a 0. to 1. value right before rendering starts, But it should have been a refactoring move without side effects. Luckily this time it seems there was a positive side effect.

> The only change I noticed is that whenever I change the settings while paused, all bars disappear until I resume playing the song. It's nothing critical, but it gets harder to evaluate subtle changes.

That's due to the spectogram code, which is still in the alpha stage. It needs a continuous time axis and fb2k produced weird time information when switching tracks. The joy of developing without any SDK documentation...

**Comment by WagnerGFX** [comment]
> Not intentionally. This version contains a couple code cleanups to make sure the spectrum amplitudes have a 0. to 1. value right before rendering starts, But it should have been a refactoring move without side effects. Luckily this time it seems there was a positive side effect.

The bands seem more "responsive" now. Overall, the cleanup was great.

> The joy of developing without any SDK documentation...

I can relate to that  😂 / 😭


Given that it's been fixed on [v0.7.5.0-alpha1](https://github.com/stuerp/foo_vis_spectrum_analyzer/releases/tag/v0.7.5.0-alpha1), I'll close it as fixed. 👍
