### ISSUE TITLE
Add option for the Bar Spectrum gradient to be applied based on bar height

### ISSUE THREAD

**Issue by WagnerGFX** [stuerp/foo_vis_spectrum_analyzer#37]
### Where?
- Configure Window > Styles > Bar Spectrum

### How it's working now:
- The Gradient colors on the Bar Spectrum Style can only be applied vertically or horizontally in a "static" way.

### What could improve:
- Add an option for the colors to be applied based on the bar's height.
- This means that each individual bar will have a different solid color based on its current height, sampled from the gradient.

### Why this is useful:
- I'm trying to reproduce the same behavior from **foo_uie_vis_channel_spectrum** where the horizontal color would have a similar effect.
- This effect allows highlighting frequency spikes with vibrant colors and blend lower values with the background using muted colors.

https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/16827309/2ac6dba7-86c1-490a-a9b2-b1cb11141627

_It's hard to see on the video due to compression and because the old visualizer only supports 2 colors, but your visualizer has a much better gradient control that can make this effect stand out more._

### System Info:
- Windows 10 22H2
- Foobar2000 v1.6.16
- Visualizer v0.7.2.0
- CPU i7-2600k
- GPU GTX 1650

**Comment by stuerp** [comment]
Interesting. Not difficult to implement but the GUI is going to be some work.

So if I understand correctly the amplitude should determine the color? Does that mean there is a lookup list that determines which color applies to an amplitude range or what?

**Comment by stuerp** [comment]
> This is 90% of it, although it's already looking quite good, the gradient is not mixing the colors in-between and just flipping to the next color when reaching the threshold. It was also quite the nice addition to also allow the effect on the other settings for the Bars and even the Curves (or is that a bug?).

The idea is that styles should behave the same for every visual element.

> If it's too GPU or CPU expensive to calculate it in real time (it probably is), you could cache in a single line of a 256x256 (or bigger) texture and sample it when needed.

I'll see what the CPU cost of interpolation is.

> ### Now, to the bugs 😅
> * Horizontal is working the same as Vertical:
>   
>   * All Bars;
>   * All Curves.

I don't get it.

> * Amplitude is using the solid color instead of the gradient:
>   
>   * Bar Top;
>   * Bar Peak Top;
>   * All Curves.

No, it does not. It's just the way a gradient works in Direct2D. There's no equivalent of a GDI+ path gradient.

> * Adding, removing and changing colors in the gradient seems to always make the % spread, removing what was previously set, but I think this one is still related to what I mentioned in [Selecting another graph on the graph list does not update some options #34]

Adding a color recalculates the positions. That was the easiest when first implementing it. I'll see if I can refine it.

**Comment by stuerp** [comment]
Have a look at https://github.com/stuerp/foo_vis_spectrum_analyzer/releases/tag/v0.7.4.0-alpha-2

**Comment by WagnerGFX** [comment]
> Have a look at https://github.com/stuerp/foo_vis_spectrum_analyzer/releases/tag/v0.7.4.0-alpha-2

It's perfect!!!  The color transitions are much smoother now. 😎
I'd say there is nothing to add to the effect itself.
You could close this request as completed or keep it open if you either plan on implementing the effect on other visual elements or still want to tidy up some things.

![smooth_amplitude](https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/16827309/5a746986-0704-488a-b0b5-fc9a941faaf7)

### About those bugs
> I don't get it.

Sorry, I wasn't very clear on that. 😅

In Styles, enabling Horizontal was not doing anything, keeping the gradient in Vertical mode, and further enabling Amplitude was making most effects completely black.
I've tested the alpha2 version and enabling Horizontal is working again, so you can forget about that part.

> No, it does not. It's just the way a gradient works in Direct2D. There's no equivalent of a GDI+ path gradient.

It's probably why it shows as all black then. I thought it was the solid color.
I was just pointing it out as it felt like a bug or that it was still not implemented for those visual elements, since it's an alpha version.
Since you are already aware of it, you can just forget about this part too.

### Gradient suggestion
> Adding a color recalculates the positions. That was the easiest when first implementing it. I'll see if I can refine it.

I suggest to not recalculate positions when changing a color, this messes with the positions when fine-tuning colors that are already in position.
Also, don't spread the colors when removing one, letting the user decide what to do.
When adding, you can just calculate the position of the new color based on its neighbors. If there are some known edge cases, then you can just go and spread the colors.

With this, spreading colors will only happen when pressing the Spread button or in rare situations.

Anyway, since this is unrelated to the request, just consider as a suggestion when improving the code later.

### A wild new bug

Right after installing alpha 2 and opening Foobar2000, the Background color in Styles reverted to none.
It's probably not related to this request, I just wanted to let you know.

**Comment by stuerp** [comment]
> ### A wild new bug
> Right after installing alpha 2 and opening Foobar2000, the Background color in Styles reverted to none. It's probably not related to this request, I just wanted to let you know.

Hey, it's alpha code ;-) You also got some work-in-progress. When implementing the styles I lost track of the User Interface and Windows color sources because I don't use them myself. They can be updated independently of the config dialog.
