### ISSUE TITLE
Custom Profile: Use as Musical & EQ Spectrum

### ISSUE THREAD

**Issue by Rexadev** [stuerp/foo_vis_spectrum_analyzer#38]
Currently i use [enhanced_Spectrum_Analyzer ](https://wiki.hydrogenaud.io/index.php?title=Foobar2000:Components/Enhanced_Spectrum_Analyzer_(foo_enhanced_spectrum_analyzer)) and foo_vis_spectrum_analyzer but would like to use just foo_vis_spectrum_analyzer as it is FOSS.
I would like to use 2 seperate settings for foo_vis_spectrum_analyzer in 2 panels with some kind of **_config profile_**.

**Comment by stuerp** [comment]
Just add 2 separate instances of the component.

**Comment by Rexadev** [comment]
@stuerp add inbuilt modes for EQ and Spectrum

**Comment by stuerp** [comment]
> @stuerp add inbuilt modes for EQ and Spectrum

I don't know what you mean. Please elaborate.

**Comment by Rexadev** [comment]
inbuilt modes for EQ and Spectrum - Preset Profiles for the component to be used as EQ and musical_spectrum

@stuerp

**Comment by stuerp** [comment]
> inbuilt modes for EQ and Spectrum - Preset Profiles for the component to be used as EQ and musical_spectrum

If you have an idea for a feature you have to describe it. I'm not clairvoyant.
