### ISSUE TITLE
[Bug] Hertz instead of notes showing

### ISSUE THREAD

**Issue by Rexadev** [stuerp/foo_vis_spectrum_analyzer#41]
## In Panel
![image](https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/62152714/c693595e-62e5-459d-a52c-a1577080b27b)

## Full screen mode
![image](https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/62152714/19476ce6-3900-4313-a279-7ff55e9e48d6)

## Latest version shows frequency in X axis in 'Panel Mode'
![image](https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/62152714/a3441e0f-1195-46b9-887c-76bd693b9fd2)

**Comment by stuerp** [comment]
Again, I don't understand what the problem is:

* fullscreen = separate instance
* separate instance = separate settings

Just change the setting in fullscreen: solved.

**Comment by Rexadev** [comment]
@stuerp how to change hertz to notes ?

**Comment by stuerp** [comment]
Please use the support forum for support questions: 
https://hydrogenaud.io/index.php/topic,125031.msg1035122
