### ISSUE TITLE
Foobar2000 crashes randomly

### ISSUE THREAD

**Issue by WagnerGFX** [stuerp/foo_vis_spectrum_analyzer#50]
### Details
This one I don't have much in terms of details and no info on how to reproduce it as the crashes seem random.

What I do have is some Foobar crash reports that mentions **_foo_vis_spectrum_analyzer_** and **_foobar2000_get_interface_** quite often.
[crash reports.zip](https://github.com/stuerp/foo_vis_spectrum_analyzer/files/14676128/crash.reports.zip)

I've been having these crashes ever since installing the component, sometimes they don't happen for the whole day, sometimes they happen just minutes after the other.

### System Info:
- Windows 10 22H2
- Foobar2000 v1.6.16
- Visualizer v0.7.5.1-alpha1

**Comment by stuerp** [comment]
While fixing the CUI lock-up I moved some thread synchronization code around. I put the code back in the previous spot and the crashes went away. I have no explanation for the crashes but I don't want to spend time on it now. I'll release a alpha2 later.

**Comment by WagnerGFX** [comment]
> I have no explanation for the crashes but I don't want to spend time on it now. I'll release an alpha2 later.

No worries, this is not a frequent issue anyway. 👍

**Comment by stuerp** [comment]
https://github.com/stuerp/foo_vis_spectrum_analyzer/releases/tag/v0.7.5.0-alpha2
