### ISSUE TITLE
Bar graph showing inaccurate frequencies after last few updates

### ISSUE THREAD

**Issue by thevudia14** [stuerp/foo_vis_spectrum_analyzer#51]
Expected:
The max frequency shown should not be greater than the song sample rate itself

Actual:
<img width="1408" alt="image" src="https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/142177869/693205e0-1d3e-4f4a-8a2a-c61c78524468">

In this example, the sample rate of the song is 44.1kHz but the graph showing more than that.

For the same song, the curve graph shows the correct frequency spread.
<img width="1410" alt="image" src="https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/142177869/79593b4d-7a21-441f-a7b4-f4f64a444c7e">

Please fix it.

**Comment by stuerp** [comment]
Can you please share the preset file for the bar graph? Because this makes no sense. The spectrum should be the same.

**Comment by thevudia14** [comment]
Where is it located? Which file format?

**Comment by stuerp** [comment]
Presets tab. Just save a test file. The default location is your fb2k profile.

**Comment by thevudia14** [comment]
[test_preset.zip](https://github.com/stuerp/foo_vis_spectrum_analyzer/files/14816430/test_preset.zip)

**Comment by stuerp** [comment]
Thx. There's nothing wrong with the spectrum as-such. The problem is caused by the high number of bars. A bar has a minimum width which causes the rendering to spill over on the right side of the component. The X-axis, however, has no such limitation and can be drawn within the bounds of the component.
Net result: A different scale factor between the bars and the X-axis.

**Comment by thevudia14** [comment]
But this did not happen until few updates ago. I reduced the number of bars, but resizing the window is causing the issue again.

**Comment by stuerp** [comment]
That's because on the support forum people kept asking me to tweak the sizing and the spacing of the spectrum bars. The next beta will have a redesigned algorithm that hopefully will please most people.

**Comment by thevudia14** [comment]
Can you point me to the version link that used to work? I will keep it until your beta release.

**Comment by stuerp** [comment]
No, because it got unnoticed. It only appears in edge case such as a high number of bands + small window size + high max. frequency.

**Comment by thevudia14** [comment]
I dont understand. I asked for a prior version which did not have the change you are talking about

**Comment by stuerp** [comment]
Have a look at https://github.com/stuerp/foo_vis_spectrum_analyzer/releases/tag/v0.7.5.0-beta2

**Comment by thevudia14** [comment]
<img width="826" alt="image" src="https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/142177869/b6c50a47-31ad-4360-b8cc-78e942a04e6c">
It's accurate now.
But there is an issue: Even though the chosen range is 20Hz-50kHz, I could see other ranges.

**Comment by stuerp** [comment]
Yet your screenshot shows 20Hz-50kHz... I'm confused.

**Comment by thevudia14** [comment]
I am talking about the borders. In old update, the empty borders wouldnt show up, on either side of 20 and 50kHz.

**Comment by stuerp** [comment]
That's by design. A pixel is a pixel. There's no way around it. Either you size the window to fit the content or you make sure there are enough bars to fill the available space.
