### ISSUE TITLE
Substantial GPU usage even when no visualisation is running / nothing is playing

### ISSUE THREAD

**Issue by Messere** [stuerp/foo_vis_spectrum_analyzer#62]
I've noticed that no matter if foobar is playing or not, spectrum analyzer is using the same amount of GPU (around 50% in my case). If I minimize foobar window or freeze the spectrum analyzer, GPU usage drops. 

I'm wondering if it would be possible to optimize GPU usage and don't put a strain on it when foobar does not play anything? I'm running foobar on small, completely fanless mini PC, and it gets hot for no reason. 

https://github.com/user-attachments/assets/34fd08c5-0cb4-415b-901e-d81933d07d9f

**Comment by stuerp** [comment]
I'm afraid I wouldn't know where to start looking. The same conditions on my system result in 0.7% GPU usage attributed to fb2k (with 3 different instances visible). When the component gets hidden f.e. in a tab all rendering stops. Are you sure your drivers are up to date?

**Comment by Messere** [comment]
Now that you mentioned the drivers - it was updated recently and I'm wondering if that's not some kind of regression. I didn't notice this GPU usage pattern before, I'll try to investigate it further. 

For now, if you can't reproduce it, then I think the issue can be closed. 
Thanks for response!

**Comment by Messere** [comment]
I've just rolled back the driver to previous version and the issue is gone. GPU usage is barely noticeable even if visualization is working. 

Intel UHD Graphics 730, v. 31.0.101.5537 installed from Windows Update is apparently broken.

**Comment by stuerp** [comment]
Glad it's not code related and that you found the reason so quickly.
